#!/usr/bin/env python3
"""US-013 acceptance test: psdata env store vs a psana ground-truth oracle.

This is the psana-oracle regression harness for psdata's env store
(:mod:`psdata.envstore`).  It proves that psdata's *pure-python*, random-access
as-of lookup for the ``epics`` and ``scan`` env stores reproduces psana's
``EnvStore`` semantics **exactly** -- same event timestamps, same as-of values
(bit-equal, no tolerance), same ``run.epicsinfo`` / ``run.scaninfo`` tables --
with no psana, mpi4py, h5py, or MPI in psdata itself.

House style mirrors ``test_regression_us005.py``:

  * a plain ``main()`` guarded by ``if __name__ == "__main__"`` -- the suite is
    NOT pytest; this file is a script run by ``python3 tests/test_envstore_us013.py``
    and MUST exit nonzero on any failure;
  * import purity is asserted (in-proc AND in a fresh subprocess) BEFORE psana
    is imported anywhere, so a later psana import cannot mask a leak;
  * the psana ground truth is regenerated by THIS harness via the shared oracle
    ``tests/_env_oracle.py`` (the only psdata-repo file allowed to import psana);
  * if psana is unavailable the psana-dependent checks SKIP cleanly (a
    ``SKIPPED`` line, exit 0) -- the psdata-only build/purity checks still run.

The comparison is STRICT -- no numeric tolerance.  Both psana and psdata decode
the *same* transition-dgram bytes, so a float that differs at all is a real
discrepancy, reported loudly, never papered over.

Reference dataset -- lives in the TEST, never in the library:
    exp="rixx45619", run=122, dir="/sdf/data/lcls/ds/prj/public01/xtc"

Needs the production psana env to generate ground truth:
    source /sdf/group/lcls/ds/ana/sw/conda2/manage/bin/psconda.sh
Iterating psana to k=3000 reads bigdata and takes a few minutes -- budget for it.
"""

import os
import subprocess
import sys

import numpy as np

# --- locate the package (parent of this tests dir) and the oracle -----------
_HERE = os.path.dirname(os.path.abspath(__file__))
_PKG_PARENT = os.path.join(os.path.dirname(_HERE), "src")  # .../<repo>/src (holds psdata/)
if _PKG_PARENT not in sys.path:
    sys.path.insert(0, _PKG_PARENT)
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)  # so ``import _env_oracle`` resolves

# Reference dataset -- golden env-store run.
EXP = "rixx45619"
RUN = 122
DIR = "/sdf/data/lcls/ds/prj/public01/xtc"

# A spread of event indices across the run (and across scan steps): the first
# few precede the first SlowUpdate (epics -> None) and step 1; k=2000/3000 land
# in scan step 2 (step_value 30000).  All are within the 10000-L1Accept run.
EVENT_KS = [0, 1, 2, 7, 50, 100, 500, 1000, 2000, 3000]

# >= 8 real epics variables.  Required: AT1K0_photon_energy, GMD_IonMesh,
# StaleFlags (rank-1 uint32 array, PV-unmapped -> '').  The rest include several
# that genuinely VARY across the sampled events / scan steps
# (photon_energy, IonMesh, StaleFlags, EXIT_SLIT_GAP, milliJoulesPerPulse_gmd,
# GMD_MeanCharge, XGMD_MeanCharge, Machine) plus two that transition None->value.
EPICS_VARS = [
    "AT1K0_photon_energy",       # varies across steps
    "GMD_IonMesh",               # varies across steps
    "StaleFlags",                # rank-1 uint32 array; PV name ''
    "EXIT_SLIT_GAP",             # varies across steps
    "milliJoulesPerPulse_gmd",   # varies across steps
    "GMD_MeanCharge",            # varies across steps
    "XGMD_MeanCharge",           # varies across steps
    "Machine",                   # varies across steps
    "MONO_ENERGY_EV",            # None -> value transition
    "AT1K0_set_GasAttenTrans",   # None -> value transition
]

# Scan step fields (ride on BeginStep).  step_docstring is the (non-JSON)
# template str {"detname": "epixhr_0", "scantype": "scan", "step": step}.
SCAN_VARS = ["step_value", "step_docstring"]


# --------------------------------------------------------------------------
# import purity -- psdata pulls in only numpy, no framework
# --------------------------------------------------------------------------
def test_import_purity_before_psana():
    """Importing the public psdata package (and reaching the env store) must NOT
    pull in a framework.  Asserted BEFORE psana is imported anywhere below."""
    import psdata
    psdata.run.assert_no_framework_imports()
    # envstore itself must be framework-free too (it delegates to format's check)
    from psdata import envstore
    envstore.assert_no_framework_imports()
    for m in ("psana", "mpi4py", "h5py", "xtcdata"):
        assert m not in sys.modules, f"{m} leaked into sys.modules on import"


def test_import_purity_subprocess():
    """In a fresh interpreter, importing psdata + envstore leaves sys.modules
    clean and pulls in numpy (only)."""
    code = (
        "import sys, psdata; "
        "from psdata import envstore; "
        "psdata.run.assert_no_framework_imports(); "
        "envstore.assert_no_framework_imports(); "
        "bad=[m for m in ('psana','mpi4py','h5py','xtcdata') if m in sys.modules]; "
        "assert not bad, bad; "
        "assert 'numpy' in sys.modules, 'numpy should be imported'; "
        "print('CLEAN')"
    )
    env = dict(os.environ, PYTHONPATH=_PKG_PARENT)
    out = subprocess.run([sys.executable, "-c", code], capture_output=True,
                         text=True, env=env)
    assert out.returncode == 0, out.stderr
    assert "CLEAN" in out.stdout, out.stdout


# --------------------------------------------------------------------------
# strict value comparison (no tolerance)
# --------------------------------------------------------------------------
def _values_equal(a, b):
    """Strict equality between a psana-oracle value ``a`` and a psdata value
    ``b``.  NO numeric tolerance -- both sides decode the same bytes.

      * None matches None (and only None).
      * Array case (rank-1 StaleFlags): the oracle serializes to a python list,
        psdata returns an ndarray -> compare shape + elementwise, dtype-agnostic.
      * str (step_docstring) -> exact string equality.
      * numeric -> exact ``==`` (bit-equal for floats), NaN==NaN treated equal.
    """
    if a is None or b is None:
        return a is None and b is None

    a_arr = isinstance(a, (list, tuple, np.ndarray))
    b_arr = isinstance(b, (list, tuple, np.ndarray))
    if a_arr or b_arr:
        if not (a_arr and b_arr):
            return False
        aa = np.asarray(a)
        bb = np.asarray(b)
        if aa.shape != bb.shape:
            return False
        return bool(np.array_equal(aa, bb))  # value-equal regardless of dtype

    if isinstance(a, str) or isinstance(b, str):
        return isinstance(a, str) and isinstance(b, str) and a == b

    # numeric: strict, NaN-aware (NaN never compares == to itself otherwise).
    fa = float(a)
    fb = float(b)
    if np.isnan(fa) or np.isnan(fb):
        return np.isnan(fa) and np.isnan(fb)
    return a == b


def _fmt(v):
    if isinstance(v, np.ndarray):
        return f"ndarray{v.shape}/{v.dtype}={v.tolist()}"
    return repr(v)


# --------------------------------------------------------------------------
# the oracle regression
# --------------------------------------------------------------------------
def run_oracle_regression():
    """Build psdata's run+index, regenerate psana ground truth via the oracle,
    and compare timestamps, epicsinfo/scaninfo, and every (event, variable)
    as-of value.  Returns ``(N, M, hard_failures)`` where N is the count of
    (event, variable) pairs compared, M the count of value mismatches, and
    ``hard_failures`` a list of non-pair failures (timestamps / info tables).

    Raises the oracle's ``PsanaUnavailable`` (caught by the caller) if psana is
    not importable -- so the psana-dependent checks SKIP cleanly.
    """
    import psdata

    # ---- psdata side: pure-python run + index + env stores ----------------
    r = psdata.open(exp=EXP, run=RUN, dir=DIR)
    idx = r.build_index()
    n_ts = len(idx.timestamps)
    kmax = max(EVENT_KS)
    assert kmax < n_ts, (
        f"event index {kmax} out of range: run has only {n_ts} L1Accept events")

    # psdata event timestamps at the sampled indices (int, ascending).
    psdata_ts = {k: int(idx.timestamps[k]) for k in EVENT_KS}

    # Building the env stores must NOT have imported a framework.
    assert "psana" not in sys.modules, "psana leaked into sys.modules via psdata"
    psdata.run.assert_no_framework_imports()

    # psdata as-of values, gathered BEFORE psana is imported (pure path).
    psdata_epics = {k: {var: r.epics(var, psdata_ts[k]) for var in EPICS_VARS}
                    for k in EVENT_KS}
    psdata_scan = {k: {var: r.scan(var, psdata_ts[k]) for var in SCAN_VARS}
                   for k in EVENT_KS}

    # psdata info tables, flattened var -> pv / var -> alg (drop the tuple key).
    psdata_epicsinfo_raw = r.epicsinfo()   # {(var, pv): pv}
    psdata_scaninfo_raw = r.scaninfo()     # {(var, alg): alg}
    psdata_epicsinfo = {k[0]: v for k, v in psdata_epicsinfo_raw.items()}
    psdata_scaninfo = {k[0]: v for k, v in psdata_scaninfo_raw.items()}
    assert "psana" not in sys.modules, "psana leaked into sys.modules via psdata"

    # ---- psana side: the oracle (imports psana; may raise PsanaUnavailable) -
    from _env_oracle import psana_env_ground_truth
    gt = psana_env_ground_truth(
        exp=EXP, run=RUN, dir=DIR,
        event_ks=EVENT_KS, epics_vars=EPICS_VARS, scan_vars=SCAN_VARS,
    )
    print(f"[oracle] psana iterated {gt['n_events_iterated']} events "
          f"(to k={kmax}); captured {len(gt['timestamps'])} timestamps")

    hard_failures = []

    # ---- (a) event timestamps must agree exactly -------------------------
    for k in EVENT_KS:
        gts = gt["timestamps"][k]
        pts = psdata_ts[k]
        if pts != gts:
            msg = (f"TIMESTAMP MISMATCH at k={k}: psdata idx.timestamps[{k}]="
                   f"{pts} != psana evt.timestamp={gts}")
            print("  [FAIL] " + msg)
            hard_failures.append(msg)
    if not any("TIMESTAMP" in f for f in hard_failures):
        print(f"[ok] event timestamps agree at all {len(EVENT_KS)} indices "
              f"{EVENT_KS}")

    # ---- (b) epicsinfo / scaninfo tables must agree ----------------------
    if psdata_epicsinfo != gt["epicsinfo"]:
        only_ps = {k: v for k, v in psdata_epicsinfo.items()
                   if gt["epicsinfo"].get(k) != v}
        only_gt = {k: v for k, v in gt["epicsinfo"].items()
                   if psdata_epicsinfo.get(k) != v}
        msg = (f"EPICSINFO MISMATCH: psdata has {len(psdata_epicsinfo)} entries, "
               f"psana {len(gt['epicsinfo'])}; psdata-only/diff={only_ps}; "
               f"psana-only/diff={only_gt}")
        print("  [FAIL] " + msg)
        hard_failures.append(msg)
    else:
        assert psdata_epicsinfo.get("StaleFlags") == "", \
            f"StaleFlags PV must be '' (got {psdata_epicsinfo.get('StaleFlags')!r})"
        print(f"[ok] epicsinfo agrees with psana run.epicsinfo "
              f"({len(psdata_epicsinfo)} entries; StaleFlags -> '')")

    if psdata_scaninfo != gt["scaninfo"]:
        msg = (f"SCANINFO MISMATCH: psdata={psdata_scaninfo} != "
               f"psana={gt['scaninfo']}")
        print("  [FAIL] " + msg)
        hard_failures.append(msg)
    else:
        print(f"[ok] scaninfo agrees with psana run.scaninfo ({psdata_scaninfo})")

    # ---- (c) every (event, variable) as-of value -------------------------
    N = 0
    M = 0
    for k in EVENT_KS:
        for var in EPICS_VARS:
            N += 1
            gval = gt["epics"][k][var]
            pval = psdata_epics[k][var]
            if not _values_equal(gval, pval):
                M += 1
                print(f"  [FAIL] epics k={k} var={var!r}: "
                      f"psana={_fmt(gval)} != psdata={_fmt(pval)}")
        for var in SCAN_VARS:
            N += 1
            gval = gt["scan"][k][var]
            pval = psdata_scan[k][var]
            if not _values_equal(gval, pval):
                M += 1
                print(f"  [FAIL] scan  k={k} var={var!r}: "
                      f"psana={_fmt(gval)} != psdata={_fmt(pval)}")

    if M == 0:
        print(f"[ok] all {N} (event, variable) as-of values bit-equal to psana")

    r.close()
    return N, M, hard_failures


def main():
    print("=" * 72)
    print("US-013 acceptance: psdata env store vs psana oracle")
    print(f"  exp={EXP!r} run={RUN} dir={DIR!r}")
    print(f"  event_ks={EVENT_KS}")
    print(f"  epics_vars ({len(EPICS_VARS)}): {EPICS_VARS}")
    print(f"  scan_vars  ({len(SCAN_VARS)}): {SCAN_VARS}")
    print("=" * 72)

    # 1. purity FIRST, before psana is imported anywhere.
    test_import_purity_before_psana()
    print("[ok] import purity (in-proc): psdata + envstore pull in no framework")
    test_import_purity_subprocess()
    print("[ok] import purity (subprocess): fresh interpreter stays clean")

    # 2/3/4/5. build psdata, regenerate psana ground truth, compare.
    from _env_oracle import PsanaUnavailable
    try:
        N, M, hard_failures = run_oracle_regression()
    except PsanaUnavailable as e:
        # psana-dependent checks skip cleanly; purity/build checks already ran.
        print(f"SKIPPED: psana is unavailable, cannot regenerate ground truth "
              f"({e}). Source psconda.sh and re-run to exercise the oracle "
              f"regression.")
        sys.exit(0)

    # 6. the required final tally line (N pairs compared, M mismatches).
    if hard_failures:
        print(f"\n{len(hard_failures)} HARD FAILURE(S) (timestamps / info tables):")
        for f in hard_failures:
            print("  - " + f)
    print(f"ENV ORACLE: {N} (event, variable) pairs compared, {M} mismatches")

    if M > 0 or hard_failures:
        print("\nFAILED: env store disagrees with psana -- see [FAIL] lines above.")
        sys.exit(1)
    print("\nALL US-013 ACCEPTANCE CHECKS PASSED")


if __name__ == "__main__":
    main()
